import { forwardRef } from 'react';
import { SITE_TITLE } from '../site-config';
import type { Locale } from '../i18n';
import type { OverviewPayload } from '../hooks/use-overview';
import type { ActivityHeatmapDay } from '../utils/activity-heatmap-data';
import { formatUsd, formatCompact, formatPercent } from '../utils/format';
import { ActivityHeatmap } from './activity-heatmap';
import { CostTrendChart } from './cost-trend-chart';
import { ChartBoundary } from './chart-helpers';

// ────────────────────────────────────────
// Types
// ────────────────────────────────────────

export interface ShareDetailCardProps {
  locale: Locale;
  totalCostUsd: number;
  totalTokens: number;
  totalSessions: number;
  activeDays: number;
  totalDays: number;
  cacheHitRate: number;
  avgDailyCostUsd: number;
  rangeLabel: string;
  topModels: Array<{ label: string; estimatedCostUsd: number }>;
  topProviders: Array<{ label: string; estimatedCostUsd: number }>;
  // Detail-specific data
  heatmapDays: ActivityHeatmapDay[];
  heatmapMetric: 'tokens' | 'sessions';
  dailyTrend: OverviewPayload['dailyTrend'];
  providerDailyTrend: OverviewPayload['providerDailyTrend'];
}

// ────────────────────────────────────────
// i18n
// ────────────────────────────────────────

const CARD_I18N = {
  en: {
    totalCost: 'Total Cost',
    totalTokens: 'Total Tokens',
    sessions: 'Sessions',
    activeDays: 'Active Days',
    cacheHitRate: 'Cache Hit',
    avgDailyCost: 'Daily Avg',
    topModels: 'Top Models',
    topProviders: 'Top Providers',
    recentActivity: 'Recent Activity',
    costTrend: 'Cost Trend',
    generatedBy: 'Generated by',
  },
  zh: {
    totalCost: '总费用',
    totalTokens: '总 Token',
    sessions: '会话数',
    activeDays: '活跃天数',
    cacheHitRate: '缓存命中',
    avgDailyCost: '日均费用',
    topModels: '热门模型',
    topProviders: '热门厂商',
    recentActivity: '近期活跃',
    costTrend: '费用趋势',
    generatedBy: '由',
  },
} as const;

// ────────────────────────────────────────
// Helpers
// ────────────────────────────────────────

function today(): string {
  const d = new Date();
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}

function Bar({ ratio, color }: { ratio: number; color: string }) {
  return (
    <div style={{ width: '100%', height: 6, borderRadius: 3, backgroundColor: '#e2e8f0', overflow: 'hidden' }}>
      <div style={{ width: `${Math.max(ratio * 100, 2)}%`, height: '100%', borderRadius: 3, backgroundColor: color }} />
    </div>
  );
}

const BAR_COLORS = ['#334155', '#64748b', '#94a3b8'];

// ────────────────────────────────────────
// ShareDetailCard
// ────────────────────────────────────────

function Inner(props: ShareDetailCardProps, ref: React.ForwardedRef<HTMLDivElement>) {
  const {
    locale, totalCostUsd, totalTokens, totalSessions,
    activeDays, totalDays, cacheHitRate, avgDailyCostUsd,
    rangeLabel, topModels, topProviders,
    heatmapDays, heatmapMetric, dailyTrend, providerDailyTrend,
  } = props;

  const t = CARD_I18N[locale];

  const kpis = [
    { label: t.totalCost, value: formatUsd(totalCostUsd), highlight: true },
    { label: t.totalTokens, value: formatCompact(totalTokens, locale) },
    { label: t.sessions, value: formatCompact(totalSessions, locale) },
    { label: t.activeDays, value: `${activeDays}/${totalDays}` },
    { label: t.cacheHitRate, value: formatPercent(cacheHitRate) },
    { label: t.avgDailyCost, value: formatUsd(avgDailyCostUsd), highlight: true },
  ];

  const modelMax = topModels[0]?.estimatedCostUsd || 1;
  const providerMax = topProviders[0]?.estimatedCostUsd || 1;

  return (
    <div
      ref={ref}
      style={{
        width: 480,
        display: 'flex',
        flexDirection: 'column',
        background: '#ffffff',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        overflow: 'hidden',
        position: 'relative',
      }}
    >
      {/* ── Header ── */}
      <div style={{ padding: '28px 28px 0' }}>
        <div style={{ fontSize: 20, fontWeight: 700, color: '#0f172a', letterSpacing: '-0.01em', lineHeight: 1.2 }}>
          {SITE_TITLE}
        </div>
        <div style={{ marginTop: 4, fontSize: 12, fontWeight: 500, color: '#94a3b8', letterSpacing: '0.02em' }}>
          {rangeLabel}
        </div>
      </div>

      {/* ── KPI Grid 2x3 ── */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 1, margin: '16px 28px 0', borderRadius: 12, overflow: 'hidden', backgroundColor: '#e2e8f0' }}>
        {kpis.map((kpi) => (
          <div key={kpi.label} style={{ backgroundColor: '#ffffff', padding: '12px 14px' }}>
            <div style={{ fontSize: 10, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em', color: '#94a3b8', lineHeight: 1 }}>
              {kpi.label}
            </div>
            <div style={{ marginTop: 6, fontSize: 20, fontWeight: 700, lineHeight: 1, letterSpacing: '-0.01em', color: kpi.highlight ? '#059669' : '#0f172a', fontVariantNumeric: 'tabular-nums' }}>
              {kpi.value}
            </div>
          </div>
        ))}
      </div>

      {/* ── Recent Activity Heatmap ── */}
      <div style={{ padding: '20px 28px 0' }}>
        <div style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em', color: '#94a3b8', marginBottom: 8 }}>
          {t.recentActivity}
        </div>
        <ActivityHeatmap days={heatmapDays} metricLabel={heatmapMetric} maxWeeks={14} />
      </div>

      {/* ── Cost Trend Chart ── */}
      <div style={{ padding: '20px 28px 0' }}>
        <div style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em', color: '#94a3b8', marginBottom: 8 }}>
          {t.costTrend}
        </div>
        <div style={{ height: 200 }}>
          <ChartBoundary name="Cost Trend">
            <CostTrendChart data={dailyTrend} providerTrend={providerDailyTrend} />
          </ChartBoundary>
        </div>
      </div>

      {/* ── Top Models ── */}
      <div style={{ padding: '20px 28px 0' }}>
        <div style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em', color: '#94a3b8', marginBottom: 8 }}>
          {t.topModels}
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {topModels.slice(0, 3).map((m, i) => (
            <div key={m.label}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 3 }}>
                <span style={{ fontSize: 12, fontWeight: 500, color: '#334155', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', flex: 1, minWidth: 0 }}>{m.label}</span>
                <span style={{ fontSize: 12, fontWeight: 600, color: '#059669', fontVariantNumeric: 'tabular-nums', flexShrink: 0, marginLeft: 8 }}>{formatUsd(m.estimatedCostUsd)}</span>
              </div>
              <Bar ratio={m.estimatedCostUsd / modelMax} color={BAR_COLORS[i] ?? BAR_COLORS[2]} />
            </div>
          ))}
        </div>
      </div>

      {/* ── Top Providers ── */}
      <div style={{ padding: '16px 28px 0' }}>
        <div style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em', color: '#94a3b8', marginBottom: 8 }}>
          {t.topProviders}
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {topProviders.slice(0, 3).map((p, i) => (
            <div key={p.label}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 3 }}>
                <span style={{ fontSize: 12, fontWeight: 500, color: '#334155', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', flex: 1, minWidth: 0 }}>{p.label}</span>
                <span style={{ fontSize: 12, fontWeight: 600, color: '#059669', fontVariantNumeric: 'tabular-nums', flexShrink: 0, marginLeft: 8 }}>{formatUsd(p.estimatedCostUsd)}</span>
              </div>
              <Bar ratio={p.estimatedCostUsd / providerMax} color={BAR_COLORS[i] ?? BAR_COLORS[2]} />
            </div>
          ))}
        </div>
      </div>

      {/* ── Footer ── */}
      <div style={{ padding: '20px 28px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <span style={{ fontSize: 11, color: '#cbd5e1', fontWeight: 500 }}>
          {locale === 'zh' ? `${t.generatedBy} AI Usage 生成` : `${t.generatedBy} AI Usage`}
        </span>
        <span style={{ fontSize: 11, color: '#cbd5e1', fontWeight: 500 }}>{today()}</span>
      </div>
    </div>
  );
}

export const ShareDetailCard = forwardRef(Inner);
ShareDetailCard.displayName = 'ShareDetailCard';
